name: Sniffer CI

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2.3.4

      - name: Install dependencies
        run: |
          sudo apt install -y nano python3 python3-pip python3-dev libnfnetlink-dev libnetfilter-queue-dev curl iptables
          sudo pip3 install scapy NetfilterQueue flashtext flake8

      - name: Test on OS
        run: |
          sudo iptables -I INPUT -j NFQUEUE --queue-num 0
          sudo iptables -I OUTPUT -j NFQUEUE --queue-num 0
          nohup sudo python3 testcase_2.py &
          sudo curl http://octobersun.com
          sudo pkill python3

      - name: Run linter
        run: |
          flake8 .




